/**
 * AWC-Connect RBAC Permissions System (Client-side)
 * 
 * Mirror of server-side permissions for frontend use
 */

// All valid roles in the system
export const ROLES = {
    MEMBER: 'member',
    CHECKIN_TEAM: 'checkin_team',
    MINISTRY_LEADER: 'ministry_leader',
    FINANCE: 'finance',
    STAFF: 'staff',
    ADMINISTRATOR: 'administrator',
    FIRST_LADY: 'first_lady',
    PASTOR: 'pastor',
    ADMIN: 'admin'
} as const;

// All permissions in the system
export const PERMISSIONS = {
    // People
    PEOPLE_READ: 'PEOPLE_READ',
    PEOPLE_WRITE: 'PEOPLE_WRITE',
    PEOPLE_DELETE: 'PEOPLE_DELETE',

    // Households
    HOUSEHOLDS_READ: 'HOUSEHOLDS_READ',
    HOUSEHOLDS_WRITE: 'HOUSEHOLDS_WRITE',
    HOUSEHOLDS_DELETE: 'HOUSEHOLDS_DELETE',

    // Ministries
    MINISTRIES_READ: 'MINISTRIES_READ',
    MINISTRIES_WRITE: 'MINISTRIES_WRITE',
    MINISTRY_MEMBERS_WRITE: 'MINISTRY_MEMBERS_WRITE',

    // Events
    EVENTS_READ: 'EVENTS_READ',
    EVENTS_REQUEST_CREATE: 'EVENTS_REQUEST_CREATE',
    EVENTS_APPROVE: 'EVENTS_APPROVE',
    EVENTS_CANCEL: 'EVENTS_CANCEL',

    // Check-in
    CHECKIN_READ: 'CHECKIN_READ',
    CHECKIN_OPEN_CLOSE: 'CHECKIN_OPEN_CLOSE',

    // Finance
    FINANCE_READ: 'FINANCE_READ',
    FINANCE_WRITE: 'FINANCE_WRITE',
    FINANCE_DELETE: 'FINANCE_DELETE',
    FINANCE_EXPORT: 'FINANCE_EXPORT',

    // Chat
    CHAT_READ: 'CHAT_READ',
    CHAT_WRITE: 'CHAT_WRITE',

    // System
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    ROLES_MANAGE: 'ROLES_MANAGE',
    AUDIT_READ: 'AUDIT_READ'
} as const;

// Role → Permissions mapping
export const rolePermissions: Record<string, string[]> = {
    [ROLES.MEMBER]: [],

    [ROLES.CHECKIN_TEAM]: [
        PERMISSIONS.PEOPLE_READ,
        PERMISSIONS.HOUSEHOLDS_READ,
        PERMISSIONS.EVENTS_READ,
        PERMISSIONS.CHECKIN_READ,
        PERMISSIONS.CHECKIN_OPEN_CLOSE,
        PERMISSIONS.CHAT_READ,
        PERMISSIONS.CHAT_WRITE,
        PERMISSIONS.SETTINGS_MANAGE
    ],

    [ROLES.MINISTRY_LEADER]: [
        PERMISSIONS.PEOPLE_READ,
        PERMISSIONS.HOUSEHOLDS_READ,
        PERMISSIONS.MINISTRIES_READ,
        PERMISSIONS.MINISTRY_MEMBERS_WRITE,
        PERMISSIONS.EVENTS_READ,
        PERMISSIONS.EVENTS_REQUEST_CREATE,
        PERMISSIONS.CHAT_READ,
        PERMISSIONS.CHAT_WRITE,
        PERMISSIONS.SETTINGS_MANAGE
    ],

    [ROLES.FINANCE]: [
        PERMISSIONS.FINANCE_READ,
        PERMISSIONS.FINANCE_WRITE,
        PERMISSIONS.FINANCE_EXPORT,
        PERMISSIONS.PEOPLE_READ,
        PERMISSIONS.HOUSEHOLDS_READ,
        PERMISSIONS.EVENTS_READ,
        PERMISSIONS.CHAT_READ,
        PERMISSIONS.CHAT_WRITE,
        PERMISSIONS.SETTINGS_MANAGE
    ],

    [ROLES.STAFF]: [
        PERMISSIONS.PEOPLE_READ,
        PERMISSIONS.PEOPLE_WRITE,
        PERMISSIONS.HOUSEHOLDS_READ,
        PERMISSIONS.HOUSEHOLDS_WRITE,
        PERMISSIONS.MINISTRIES_READ,
        PERMISSIONS.MINISTRIES_WRITE,
        PERMISSIONS.EVENTS_READ,
        PERMISSIONS.EVENTS_REQUEST_CREATE,
        PERMISSIONS.CHECKIN_READ,
        PERMISSIONS.CHAT_READ,
        PERMISSIONS.CHAT_WRITE,
        PERMISSIONS.AUDIT_READ,
        PERMISSIONS.SETTINGS_MANAGE
    ],

    [ROLES.ADMINISTRATOR]: [
        PERMISSIONS.PEOPLE_READ,
        PERMISSIONS.PEOPLE_WRITE,
        PERMISSIONS.HOUSEHOLDS_READ,
        PERMISSIONS.HOUSEHOLDS_WRITE,
        PERMISSIONS.MINISTRIES_READ,
        PERMISSIONS.MINISTRIES_WRITE,
        PERMISSIONS.EVENTS_READ,
        PERMISSIONS.EVENTS_REQUEST_CREATE,
        PERMISSIONS.EVENTS_APPROVE,
        PERMISSIONS.EVENTS_CANCEL,
        PERMISSIONS.CHECKIN_READ,
        PERMISSIONS.CHECKIN_OPEN_CLOSE,
        PERMISSIONS.FINANCE_READ,
        PERMISSIONS.CHAT_READ,
        PERMISSIONS.CHAT_WRITE,
        PERMISSIONS.SETTINGS_MANAGE,
        PERMISSIONS.AUDIT_READ
    ],

    [ROLES.FIRST_LADY]: [
        PERMISSIONS.PEOPLE_READ,
        PERMISSIONS.PEOPLE_WRITE,
        PERMISSIONS.PEOPLE_DELETE,
        PERMISSIONS.HOUSEHOLDS_READ,
        PERMISSIONS.HOUSEHOLDS_WRITE,
        PERMISSIONS.HOUSEHOLDS_DELETE,
        PERMISSIONS.MINISTRIES_READ,
        PERMISSIONS.MINISTRIES_WRITE,
        PERMISSIONS.MINISTRY_MEMBERS_WRITE,
        PERMISSIONS.EVENTS_READ,
        PERMISSIONS.EVENTS_REQUEST_CREATE,
        PERMISSIONS.EVENTS_APPROVE,
        PERMISSIONS.EVENTS_CANCEL,
        PERMISSIONS.CHECKIN_READ,
        PERMISSIONS.CHECKIN_OPEN_CLOSE,
        PERMISSIONS.FINANCE_READ,
        PERMISSIONS.FINANCE_WRITE,
        PERMISSIONS.FINANCE_EXPORT,
        PERMISSIONS.CHAT_READ,
        PERMISSIONS.CHAT_WRITE,
        PERMISSIONS.SETTINGS_MANAGE,
        PERMISSIONS.ROLES_MANAGE,
        PERMISSIONS.AUDIT_READ
    ],

    [ROLES.PASTOR]: [
        PERMISSIONS.PEOPLE_READ,
        PERMISSIONS.PEOPLE_WRITE,
        PERMISSIONS.PEOPLE_DELETE,
        PERMISSIONS.HOUSEHOLDS_READ,
        PERMISSIONS.HOUSEHOLDS_WRITE,
        PERMISSIONS.HOUSEHOLDS_DELETE,
        PERMISSIONS.MINISTRIES_READ,
        PERMISSIONS.MINISTRIES_WRITE,
        PERMISSIONS.MINISTRY_MEMBERS_WRITE,
        PERMISSIONS.EVENTS_READ,
        PERMISSIONS.EVENTS_REQUEST_CREATE,
        PERMISSIONS.EVENTS_APPROVE,
        PERMISSIONS.EVENTS_CANCEL,
        PERMISSIONS.CHECKIN_READ,
        PERMISSIONS.CHECKIN_OPEN_CLOSE,
        PERMISSIONS.FINANCE_READ,
        PERMISSIONS.FINANCE_WRITE,
        PERMISSIONS.FINANCE_EXPORT,
        PERMISSIONS.CHAT_READ,
        PERMISSIONS.CHAT_WRITE,
        PERMISSIONS.SETTINGS_MANAGE,
        PERMISSIONS.ROLES_MANAGE,
        PERMISSIONS.AUDIT_READ
    ],

    [ROLES.ADMIN]: [
        PERMISSIONS.PEOPLE_READ,
        PERMISSIONS.PEOPLE_WRITE,
        PERMISSIONS.PEOPLE_DELETE,
        PERMISSIONS.HOUSEHOLDS_READ,
        PERMISSIONS.HOUSEHOLDS_WRITE,
        PERMISSIONS.HOUSEHOLDS_DELETE,
        PERMISSIONS.MINISTRIES_READ,
        PERMISSIONS.MINISTRIES_WRITE,
        PERMISSIONS.MINISTRY_MEMBERS_WRITE,
        PERMISSIONS.EVENTS_READ,
        PERMISSIONS.EVENTS_REQUEST_CREATE,
        PERMISSIONS.EVENTS_APPROVE,
        PERMISSIONS.EVENTS_CANCEL,
        PERMISSIONS.CHECKIN_READ,
        PERMISSIONS.CHECKIN_OPEN_CLOSE,
        PERMISSIONS.FINANCE_READ,
        PERMISSIONS.FINANCE_WRITE,
        PERMISSIONS.FINANCE_DELETE,
        PERMISSIONS.FINANCE_EXPORT,
        PERMISSIONS.CHAT_READ,
        PERMISSIONS.CHAT_WRITE,
        PERMISSIONS.SETTINGS_MANAGE,
        PERMISSIONS.ROLES_MANAGE,
        PERMISSIONS.AUDIT_READ
    ]
};

// Staff roles (can access /staff/* portal)
export const STAFF_ROLES = [
    ROLES.ADMIN,
    ROLES.PASTOR,
    ROLES.FIRST_LADY,
    ROLES.ADMINISTRATOR,
    ROLES.STAFF,
    ROLES.FINANCE,
    ROLES.MINISTRY_LEADER,
    ROLES.CHECKIN_TEAM
];

/**
 * Check if a role has a specific permission
 */
export function hasPermission(role: string | undefined, permission: string): boolean {
    if (!role || !permission) return false;
    return rolePermissions[role]?.includes(permission) || false;
}

/**
 * Check if a role can access staff portal
 */
export function isStaffRole(role: string | undefined): boolean {
    if (!role) return false;
    return (STAFF_ROLES as readonly string[]).includes(role);
}

/**
 * Get all permissions for a role
 */
export function getRolePermissions(role: string): string[] {
    return rolePermissions[role] || [];
}
